### ISSUE TITLE
source code of docker image cannot be updated

### ISSUE THREAD

**Issue by bhaveshsilversky** [kinecosystem/kin-python-bootstrap#8]
I have successfully deployed the kin python bootstrap docker image in ubuntu 18.04 server
I am trying to updating the source code and rebuild the docker image using the following command:

`sudo docker-compose up -d --force-recreate --build`

and try to view the source code of docker using the following command

`sudo docker exec -t -i kin-python-bootstrap_bootstrap_1 /bin/bash`

here kin-python-bootstrap_bootstrap_1 is the docker name

but the source inside the docker does not update.
how can i alter the source code and changes get effected in docker

**Comment by lherna1371** [comment]
Having the same issue, thanks for posting.

**Comment by bhaveshsilversky** [comment]
Did you get alternative or workaround for this

**Comment by bhaveshsilversky** [comment]
I am able to update the source by changing docker-compose.yaml file

**Comment by lherna1371** [comment]
Don't have a workaround, do too figure this out?

**Comment by lherna1371** [comment]
Question. So, you made changes to the source code, created a new image and updated the docker-compose.yml to point to your new image? I've done this and still don't see changes. I simply created a new route and still get more repsonse to that endpoint when I to what I listed and run docker-compose up. Anything I may have missed? Thanks.

**Comment by bhaveshsilversky** [comment]
The steps i followed are as follows
1. thd docker compose yml file content 

```
version: '3'

services:
  bootstrap:
    image: kinecosystem/python-bootstrap:1.0.0
    ports:
      - 8000:8000
    environment:
      SEED:
      HORIZON_ENDPOINT:
      NETWORK_PASSPHRASE:
      APP_ID:
      CHANNEL_COUNT: 100
      CHANNEL_SALT:
      CHANNEL_STARTING_BALANCE:
      PORT: 8000
      LOG_LEVEL: 'INFO'

    volumes:
      - ./bootstrap:/opt/bootstrap  

```
i have added the following extra line which make the work done
...
 volumes:
      - ./bootstrap:/opt/bootstrap  
...
./bootstrap: is the source code relative path 
/opt/bootstrap : is the destination path inside the container

2. after i make any changes in source then i run the following command
...
sudo docker-compose up -d --force-recreate --build
...

3. if you want to confirm the changes are being pushed to container than use following command 
...
sudo docker exec -t -i kin-python-bootstrap_bootstrap_1 /bin/bash
...
kin-python-bootstrap_bootstrap_1 is the name of the container
the above command will give shell access to the container in read only mode in which you can check if the changes made in source code have been reflected in container or not
